In [48]:
import pandas as pd

df = pd.read_csv("../datos/datos.xls", header=0)
df.head()

   Transaction           Item         date_time period_day weekday_weekend
0            1          Bread  30-10-2016 09:58    morning         weekend
1            2   Scandinavian  30-10-2016 10:05    morning         weekend
2            2   Scandinavian  30-10-2016 10:05    morning         weekend
3            3  Hot chocolate  30-10-2016 10:07    morning         weekend
4            3            Jam  30-10-2016 10:07    morning         weekend

In [49]:
df = df.groupby(list(df.columns), as_index=False).size().rename(columns={"size": "count"})
df.head()

,Transaction,Item,date_time,period_day,weekday_weekend,count
0,1,Bread,30-10-2016 09:58,morning,weekend,1
1,2,Scandinavian,30-10-2016 10:05,morning,weekend,2
2,3,Cookies,30-10-2016 10:07,morning,weekend,1
3,3,Hot chocolate,30-10-2016 10:07,morning,weekend,1
4,3,Jam,30-10-2016 10:07,morning,weekend,1

In [50]:
order = list(df["period_day"].unique())
order

['morning', 'afternoon', 'evening', 'night']

In [51]:
df["date_time"] = pd.to_datetime(df["date_time"], format="%d-%m-%Y %H:%M")

df["weekday"] = df["weekday_weekend"] == "weekday"
df = df.drop(columns="weekday_weekend")

df["period_day"] = pd.Categorical(df["period_day"], categories=order, ordered=True).codes

In [52]:
df.head(10)

   Transaction           Item           date_time  period_day  count  weekday
0            1          Bread 2016-10-30 09:58:00           0      1    False
1            2   Scandinavian 2016-10-30 10:05:00           0      2    False
2            3        Cookies 2016-10-30 10:07:00           0      1    False
3            3  Hot chocolate 2016-10-30 10:07:00           0      1    False
4            3            Jam 2016-10-30 10:07:00           0      1    False
5            4         Muffin 2016-10-30 10:08:00           0      1    False
6            5          Bread 2016-10-30 10:13:00           0      1    False
7            5         Coffee 2016-10-30 10:13:00           0      1    False
8            5         Pastry 2016-10-30 10:13:00           0      1    False
9            6      Medialuna 2016-10-30 10:16:00           0      1    False

In [55]:
df.to_csv("../datos/datos_preproc.csv", sep=",", header=True, index=False)